
# If MySQL is disabled, we will use SQLite
mysql:
  enabled: false
  host: 'localhost'
  database: 'database'
  username: 'username'
  password: 'password'
  port: 3306
  useSSL: false

# How many mobcoins should player start with
starting-balance: 0

mobcoins:
  type: VIRTUAL

mobcoinsItem:
  material: SUNFLOWER
  name: "&e&lMobcoins &7(Right Click)"
  glow: false
  lore:
    - '&7You can use mobcoins to purchase'
    - '&7items on /mobcoins shop!'
    - ''
    - '&6{amount} coins &7are stored in this item!'
    - ''
    - '&6Right click to redeem!'

sounds:
  onCoinsRedeem:
    enabled: true
    name: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0

messages:
  prefix: "&e[MobCoins]"
  noPermission: "{prefix} &cYou don't have enough permission!"
  balance: "{prefix} &fYour coins: &e{coins}"
  balanceOthers: "{prefix} &f{player}'s coins: &e{coins}"
  playerNotExists: "{prefix} &cThat player is not online!"
  notInt: "{prefix} &cThe amount argument is not a number!"
  addCoins: "{prefix} &aYou have given &e{amount} {type} coins &ato &e{player}"
  addCoinsOthers: "{prefix} &aYou have received &e{amount} {type} coins&a."
  invalidType: "{prefix} &cInvalid types! &7(physical, virtual)"
  removeCoins: "{prefix} &aYou have removed &e{amount} coins &afrom &e{player}"
  removeCoinsOthers: "{prefix} &e{amount} coins &ahas been removed from your account!"
  setCoins: "{prefix} &aYou have set &e{player} &acoins to &e{amount}"
  setCoinsOthers: "{prefix} &aYour coins has been set to &e{amount}"
  notEnoughCoins: "{prefix} &cYou don't have enough coins!"
  selfPay: "{prefix} &cYou can not give yourself coins!"
  pay: "{prefix} &aYou have given &e{amount} coins &ato &e{player}"
  payOthers: "{prefix} &aYou have received &e{amount} coins &afrom &e{player}"
  redeem: "{prefix} &aYou have redeemed &e{amount} coins&a."
  help:
    - "Current Help"
    - "/mobcoins help"
    - "/mobcoins balance"
  helpAdmin:
    - "Admin Help"
    - "/mobcoins help"
    - "/mobcoins balance"