name: TheOnly-MobCoins
version: 1.0.0
main: me.aglerr.mobcoins.MobCoins
author: aglerr
api-version: 1.13
softdepend: [WildStacker, MythicMobs, PlaceholderAPI]

commands:
  mobcoins:
    aliases: [mc, mobcoin]