name: TheOnly-MobCoins
version: 1.0.5
main: me.aglerr.mobcoins.MobCoins
author: aglerr
api-version: 1.13
softdepend: [WildStacker, MythicMobs, SuperMobCoins, KrakenMobCoins]
depend: [PlaceholderAPI]

commands:
  mobcoins:
    aliases: []