name: TheOnly-MobCoins
version: 1.1.0
main: me.aglerr.mobcoins.MobCoins
author: aglerr
api-version: 1.13
softdepend: [WildStacker, MythicMobs, SuperMobCoins, KrakenMobCoins, JetsMinion]
depend: [PlaceholderAPI]

commands:
  mobcoins:
    aliases: []