name: TheOnly-MobCoins
version: 1.0.3
main: me.aglerr.mobcoins.MobCoins
author: aglerr
api-version: 1.13
softdepend: [WildStacker, MythicMobs]
depend: [PlaceholderAPI]

commands:
  mobcoins:
    aliases: []