
# If MySQL is disabled, we will use SQLite
mysql:
  enabled: false
  host: 'localhost'
  database: 'database'
  username: 'username'
  password: 'password'
  port: 3306
  useSSL: false

# How many mobcoins should player start with
starting-balance: 0

mobcoins:
  physicalMobCoin: false
  disableMobCoinFromSpawner: true

# What world should we disable player from receiving mobcoin?
disabledWorlds:
  - 'exampleWorld'
  - 'theonly_world'

# MobCoins items that will be used for physical mobcoin.
mobcoinsItem:
  material: SUNFLOWER
  name: "&e&lMobcoins &7(Right Click)"
  glow: false
  lore:
    - '&7You can use mobcoins to purchase'
    - '&7items on /mobcoins shop!'
    - ''
    - '&6{amount} coins &7are stored in this item!'
    - ''
    - '&6Right click to redeem!'

# If you enabled this mode, player will receive notification
# every x amount of seconds on how much that they receive
# mobcoins in that time.
# Configuration Information:
#   (announceEvery) the time is in seconds, 300 seconds = 5 minute.
#   (receiveAfterMessage) should player receive mobcoins after the notification?
#
salaryMode:
  enabled: true
  announceEvery: 300
  receiveAfterMessage: false
  messages:
    - ''
    - '&6&l[!] Mob &e&lCoins &7(Earning Summary)'
    - '&fYou have earned &6{amount} coins &fin the past 5 minutes!'
    - ''



sounds:
  onCoinsRedeem:
    enabled: true
    name: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
  onCoinsReceived:
    enabled: true
    name: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 1.0

# Format Information
# titleKey:
#   (enabled) should we send this title to player?
#   (title) the title on the titlebar
#   (subtitle) the subtitle on the titlebar
#   (fadeIn) fade in animation, time in ticks (20 ticks = 1 second)
#   (stay) how long should the title stay, time in ticks (20 ticks = 1 second)
#   (fadeOut) fade out animation, time in ticks (20 ticks = 1 second)
titles:
  onCoinsReceived:
    enabled: true
    title: "&e&l+{amount} MobCoins"
    subTitle: "&fYou just received {amount} coins"
    fadeIn: 20
    stay: 40
    fadeOut: 20

actionBar:
  onCoinsReceived:
    enabled: true
    message: "&a+{amount} MobCoins"

messages:
  prefix: "&e[MobCoins]"
  noPermission: "{prefix} &cYou don't have enough permission!"
  balance: "{prefix} &fYour coins: &e{coins}"
  balanceOthers: "{prefix} &f{player}'s coins: &e{coins}"
  playerNotExists: "{prefix} &cThat player is not online!"
  notInt: "{prefix} &cThe amount argument is not a number!"
  addCoins: "{prefix} &aYou have given &e{amount} &a{type} coins to &e{player}"
  addCoinsOthers: "{prefix} &aYou have received &e{amount} &a{type} coins."
  invalidType: "{prefix} &cInvalid types! &7(physical, virtual)"
  removeCoins: "{prefix} &aYou have removed &e{amount} &acoins from &e{player}"
  removeCoinsOthers: "{prefix} &e{amount} &acoins has been removed from your account!"
  setCoins: "{prefix} &aYou have set &e{player} &acoins to &e{amount}"
  setCoinsOthers: "{prefix} &aYour coins has been set to &e{amount}"
  notEnoughCoins: "{prefix} &cYou don't have enough coins!"
  selfPay: "{prefix} &cYou can not give yourself coins!"
  pay: "{prefix} &aYou have given &e{amount} &acoins to &e{player}"
  payOthers: "{prefix} &aYou have received &e{amount} &acoins from &e{player}"
  redeem: "{prefix} &aYou have redeemed &e{amount} &acoins."
  coinsReceived: "{prefix} &aYou have received &e{amount} &acoins."
  help:
    - "Current Help"
    - "/mobcoins help"
    - "/mobcoins balance"
  helpAdmin:
    - "Admin Help"
    - "/mobcoins help"
    - "/mobcoins balance"