
# If MySQL is disabled, we will use SQLite
mysql:
  enabled: false
  host: 'localhost'
  database: 'database'
  username: 'username'
  password: 'password'
  port: 3306
  useSSL: false

messages:
  prefix: "&e[TheOnly-MobCoins]"
  noPermission: "&cYou don't have enough permission!"
  balance: "{prefix} &fYour coins: &e{coins}"
  help:
    - "Current Help"
    - "/mobcoins help"
    - "/mobcoins balance"
  helpAdmin:
    - "Admin Help"
    - "/mobcoins help"
    - "/mobcoins balance"